name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'

      - name: Build & test with coverage
        run: mvn -B clean verify

      - name: Upload JaCoCo report as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Print coverage summary
        run: |
          REPORT=target/site/jacoco/jacoco.xml
          if [ -f "$REPORT" ]; then
            echo "Coverage XML generated at $REPORT"
          else
            echo "Coverage report missing"; exit 1
          fi